from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy_utils import JSONType 
from sqlalchemy import func
from .db_connector import Base, engine 
import datetime

# --- Utility: Create Tables on Startup ---

def init_db():
    """Initializes the database tables based on the SQLAlchemy models."""
    Base.metadata.create_all(bind=engine)

# --- User Model (Authentication & Roles) ---
class User(Base):
    """
    Represents a user in the system (Student or Recruiter).
    """
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    # Stores the hashed password (using bcrypt)
    hashed_password = Column(String, nullable=False)
    # Defines the role: 'student' or 'recruiter'
    role = Column(String, default='student', nullable=False) 
    is_active = Column(Integer, default=1) # Simple integer flag for active status

    # Relationships
    profile = relationship("UserProfile", back_populates="owner", uselist=False)
    applications = relationship("Application", back_populates="student")
    posted_jobs = relationship("Internship", back_populates="recruiter") 

# --- User Profile Model (Student Data for ML) ---
class UserProfile(Base):
    """
    Stores student-specific data and the ML embedding of their resume/skills.
    """
    __tablename__ = "user_profiles"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    
    full_name = Column(String, nullable=True)
    # The vector embedding generated by Sentence Transformers
    embedding = Column(JSONType, nullable=True) 
    last_updated = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationship to User
    owner = relationship("User", back_populates="profile")


# --- Internship Model (Job Posting) ---
class Internship(Base):
    """
    Represents a single job posting, including the vector embedding.
    """
    __tablename__ = "internships"
    
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True, nullable=False)
    description = Column(String, nullable=False)
    # Store required_skills as JSON list
    required_skills = Column(JSONType, default=[]) 
    
    
    recruiter_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    
    
    embedding = Column(JSONType, nullable=False) 
    
    date_posted = Column(DateTime, default=datetime.datetime.utcnow)

    
    recruiter = relationship("User", back_populates="posted_jobs")
    job_applications = relationship("Application", back_populates="job")


# --- Application Model (Tracking) ---
class Application(Base):
    """
    Tracks which student has applied to which job.
    """
    __tablename__ = "applications"
    
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    job_id = Column(Integer, ForeignKey("internships.id"), nullable=False)
    
    status = Column(String, default="Pending") # e.g., Pending, Reviewed, Interview, Rejected
    applied_date = Column(DateTime, default=datetime.datetime.utcnow)
    resume_path = Column(String, nullable=True) # <-- ADD THIS LINE
    # Relationships
    student = relationship("User", back_populates="applications")
    job = relationship("Internship", back_populates="job_applications")